// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package database

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CatalogID, b.ko.Spec.CatalogID) {
		delta.Add("Spec.CatalogID", a.ko.Spec.CatalogID, b.ko.Spec.CatalogID)
	} else if a.ko.Spec.CatalogID != nil && b.ko.Spec.CatalogID != nil {
		if *a.ko.Spec.CatalogID != *b.ko.Spec.CatalogID {
			delta.Add("Spec.CatalogID", a.ko.Spec.CatalogID, b.ko.Spec.CatalogID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput, b.ko.Spec.DatabaseInput) {
		delta.Add("Spec.DatabaseInput", a.ko.Spec.DatabaseInput, b.ko.Spec.DatabaseInput)
	} else if a.ko.Spec.DatabaseInput != nil && b.ko.Spec.DatabaseInput != nil {
		if len(a.ko.Spec.DatabaseInput.CreateTableDefaultPermissions) != len(b.ko.Spec.DatabaseInput.CreateTableDefaultPermissions) {
			delta.Add("Spec.DatabaseInput.CreateTableDefaultPermissions", a.ko.Spec.DatabaseInput.CreateTableDefaultPermissions, b.ko.Spec.DatabaseInput.CreateTableDefaultPermissions)
		} else if len(a.ko.Spec.DatabaseInput.CreateTableDefaultPermissions) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.DatabaseInput.CreateTableDefaultPermissions, b.ko.Spec.DatabaseInput.CreateTableDefaultPermissions) {
				delta.Add("Spec.DatabaseInput.CreateTableDefaultPermissions", a.ko.Spec.DatabaseInput.CreateTableDefaultPermissions, b.ko.Spec.DatabaseInput.CreateTableDefaultPermissions)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.Description, b.ko.Spec.DatabaseInput.Description) {
			delta.Add("Spec.DatabaseInput.Description", a.ko.Spec.DatabaseInput.Description, b.ko.Spec.DatabaseInput.Description)
		} else if a.ko.Spec.DatabaseInput.Description != nil && b.ko.Spec.DatabaseInput.Description != nil {
			if *a.ko.Spec.DatabaseInput.Description != *b.ko.Spec.DatabaseInput.Description {
				delta.Add("Spec.DatabaseInput.Description", a.ko.Spec.DatabaseInput.Description, b.ko.Spec.DatabaseInput.Description)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.FederatedDatabase, b.ko.Spec.DatabaseInput.FederatedDatabase) {
			delta.Add("Spec.DatabaseInput.FederatedDatabase", a.ko.Spec.DatabaseInput.FederatedDatabase, b.ko.Spec.DatabaseInput.FederatedDatabase)
		} else if a.ko.Spec.DatabaseInput.FederatedDatabase != nil && b.ko.Spec.DatabaseInput.FederatedDatabase != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName, b.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName) {
				delta.Add("Spec.DatabaseInput.FederatedDatabase.ConnectionName", a.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName, b.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName)
			} else if a.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName != nil && b.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName != nil {
				if *a.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName != *b.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName {
					delta.Add("Spec.DatabaseInput.FederatedDatabase.ConnectionName", a.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName, b.ko.Spec.DatabaseInput.FederatedDatabase.ConnectionName)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.FederatedDatabase.Identifier, b.ko.Spec.DatabaseInput.FederatedDatabase.Identifier) {
				delta.Add("Spec.DatabaseInput.FederatedDatabase.Identifier", a.ko.Spec.DatabaseInput.FederatedDatabase.Identifier, b.ko.Spec.DatabaseInput.FederatedDatabase.Identifier)
			} else if a.ko.Spec.DatabaseInput.FederatedDatabase.Identifier != nil && b.ko.Spec.DatabaseInput.FederatedDatabase.Identifier != nil {
				if *a.ko.Spec.DatabaseInput.FederatedDatabase.Identifier != *b.ko.Spec.DatabaseInput.FederatedDatabase.Identifier {
					delta.Add("Spec.DatabaseInput.FederatedDatabase.Identifier", a.ko.Spec.DatabaseInput.FederatedDatabase.Identifier, b.ko.Spec.DatabaseInput.FederatedDatabase.Identifier)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.LocationURI, b.ko.Spec.DatabaseInput.LocationURI) {
			delta.Add("Spec.DatabaseInput.LocationURI", a.ko.Spec.DatabaseInput.LocationURI, b.ko.Spec.DatabaseInput.LocationURI)
		} else if a.ko.Spec.DatabaseInput.LocationURI != nil && b.ko.Spec.DatabaseInput.LocationURI != nil {
			if *a.ko.Spec.DatabaseInput.LocationURI != *b.ko.Spec.DatabaseInput.LocationURI {
				delta.Add("Spec.DatabaseInput.LocationURI", a.ko.Spec.DatabaseInput.LocationURI, b.ko.Spec.DatabaseInput.LocationURI)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.Name, b.ko.Spec.DatabaseInput.Name) {
			delta.Add("Spec.DatabaseInput.Name", a.ko.Spec.DatabaseInput.Name, b.ko.Spec.DatabaseInput.Name)
		} else if a.ko.Spec.DatabaseInput.Name != nil && b.ko.Spec.DatabaseInput.Name != nil {
			if *a.ko.Spec.DatabaseInput.Name != *b.ko.Spec.DatabaseInput.Name {
				delta.Add("Spec.DatabaseInput.Name", a.ko.Spec.DatabaseInput.Name, b.ko.Spec.DatabaseInput.Name)
			}
		}
		if len(a.ko.Spec.DatabaseInput.Parameters) != len(b.ko.Spec.DatabaseInput.Parameters) {
			delta.Add("Spec.DatabaseInput.Parameters", a.ko.Spec.DatabaseInput.Parameters, b.ko.Spec.DatabaseInput.Parameters)
		} else if len(a.ko.Spec.DatabaseInput.Parameters) > 0 {
			if !ackcompare.MapStringStringPEqual(a.ko.Spec.DatabaseInput.Parameters, b.ko.Spec.DatabaseInput.Parameters) {
				delta.Add("Spec.DatabaseInput.Parameters", a.ko.Spec.DatabaseInput.Parameters, b.ko.Spec.DatabaseInput.Parameters)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.TargetDatabase, b.ko.Spec.DatabaseInput.TargetDatabase) {
			delta.Add("Spec.DatabaseInput.TargetDatabase", a.ko.Spec.DatabaseInput.TargetDatabase, b.ko.Spec.DatabaseInput.TargetDatabase)
		} else if a.ko.Spec.DatabaseInput.TargetDatabase != nil && b.ko.Spec.DatabaseInput.TargetDatabase != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.TargetDatabase.CatalogID, b.ko.Spec.DatabaseInput.TargetDatabase.CatalogID) {
				delta.Add("Spec.DatabaseInput.TargetDatabase.CatalogID", a.ko.Spec.DatabaseInput.TargetDatabase.CatalogID, b.ko.Spec.DatabaseInput.TargetDatabase.CatalogID)
			} else if a.ko.Spec.DatabaseInput.TargetDatabase.CatalogID != nil && b.ko.Spec.DatabaseInput.TargetDatabase.CatalogID != nil {
				if *a.ko.Spec.DatabaseInput.TargetDatabase.CatalogID != *b.ko.Spec.DatabaseInput.TargetDatabase.CatalogID {
					delta.Add("Spec.DatabaseInput.TargetDatabase.CatalogID", a.ko.Spec.DatabaseInput.TargetDatabase.CatalogID, b.ko.Spec.DatabaseInput.TargetDatabase.CatalogID)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName, b.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName) {
				delta.Add("Spec.DatabaseInput.TargetDatabase.DatabaseName", a.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName, b.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName)
			} else if a.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName != nil && b.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName != nil {
				if *a.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName != *b.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName {
					delta.Add("Spec.DatabaseInput.TargetDatabase.DatabaseName", a.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName, b.ko.Spec.DatabaseInput.TargetDatabase.DatabaseName)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DatabaseInput.TargetDatabase.Region, b.ko.Spec.DatabaseInput.TargetDatabase.Region) {
				delta.Add("Spec.DatabaseInput.TargetDatabase.Region", a.ko.Spec.DatabaseInput.TargetDatabase.Region, b.ko.Spec.DatabaseInput.TargetDatabase.Region)
			} else if a.ko.Spec.DatabaseInput.TargetDatabase.Region != nil && b.ko.Spec.DatabaseInput.TargetDatabase.Region != nil {
				if *a.ko.Spec.DatabaseInput.TargetDatabase.Region != *b.ko.Spec.DatabaseInput.TargetDatabase.Region {
					delta.Add("Spec.DatabaseInput.TargetDatabase.Region", a.ko.Spec.DatabaseInput.TargetDatabase.Region, b.ko.Spec.DatabaseInput.TargetDatabase.Region)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
