// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package table

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	// CatalogID is auto-populated by AWS and not user-settable; skip comparison.
	if ackcompare.HasNilDifference(a.ko.Spec.DatabaseName, b.ko.Spec.DatabaseName) {
		delta.Add("Spec.DatabaseName", a.ko.Spec.DatabaseName, b.ko.Spec.DatabaseName)
	} else if a.ko.Spec.DatabaseName != nil && b.ko.Spec.DatabaseName != nil {
		if *a.ko.Spec.DatabaseName != *b.ko.Spec.DatabaseName {
			delta.Add("Spec.DatabaseName", a.ko.Spec.DatabaseName, b.ko.Spec.DatabaseName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Owner, b.ko.Spec.Owner) {
		delta.Add("Spec.Owner", a.ko.Spec.Owner, b.ko.Spec.Owner)
	} else if a.ko.Spec.Owner != nil && b.ko.Spec.Owner != nil {
		if *a.ko.Spec.Owner != *b.ko.Spec.Owner {
			delta.Add("Spec.Owner", a.ko.Spec.Owner, b.ko.Spec.Owner)
		}
	}
	if len(a.ko.Spec.Parameters) != len(b.ko.Spec.Parameters) {
		delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
	} else if len(a.ko.Spec.Parameters) > 0 {
		if !ackcompare.MapStringStringPEqual(a.ko.Spec.Parameters, b.ko.Spec.Parameters) {
			delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
		}
	}
	if len(a.ko.Spec.PartitionKeys) != len(b.ko.Spec.PartitionKeys) {
		delta.Add("Spec.PartitionKeys", a.ko.Spec.PartitionKeys, b.ko.Spec.PartitionKeys)
	} else if len(a.ko.Spec.PartitionKeys) > 0 {
		if !equality.Semantic.DeepEqual(a.ko.Spec.PartitionKeys, b.ko.Spec.PartitionKeys) {
			delta.Add("Spec.PartitionKeys", a.ko.Spec.PartitionKeys, b.ko.Spec.PartitionKeys)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Retention, b.ko.Spec.Retention) {
		delta.Add("Spec.Retention", a.ko.Spec.Retention, b.ko.Spec.Retention)
	} else if a.ko.Spec.Retention != nil && b.ko.Spec.Retention != nil {
		if *a.ko.Spec.Retention != *b.ko.Spec.Retention {
			delta.Add("Spec.Retention", a.ko.Spec.Retention, b.ko.Spec.Retention)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StorageDescriptor, b.ko.Spec.StorageDescriptor) {
		delta.Add("Spec.StorageDescriptor", a.ko.Spec.StorageDescriptor, b.ko.Spec.StorageDescriptor)
	} else if a.ko.Spec.StorageDescriptor != nil && b.ko.Spec.StorageDescriptor != nil {
		if !equality.Semantic.DeepEqual(a.ko.Spec.StorageDescriptor, b.ko.Spec.StorageDescriptor) {
			delta.Add("Spec.StorageDescriptor", a.ko.Spec.StorageDescriptor, b.ko.Spec.StorageDescriptor)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TableType, b.ko.Spec.TableType) {
		delta.Add("Spec.TableType", a.ko.Spec.TableType, b.ko.Spec.TableType)
	} else if a.ko.Spec.TableType != nil && b.ko.Spec.TableType != nil {
		if *a.ko.Spec.TableType != *b.ko.Spec.TableType {
			delta.Add("Spec.TableType", a.ko.Spec.TableType, b.ko.Spec.TableType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TargetTable, b.ko.Spec.TargetTable) {
		delta.Add("Spec.TargetTable", a.ko.Spec.TargetTable, b.ko.Spec.TargetTable)
	} else if a.ko.Spec.TargetTable != nil && b.ko.Spec.TargetTable != nil {
		if !equality.Semantic.DeepEqual(a.ko.Spec.TargetTable, b.ko.Spec.TargetTable) {
			delta.Add("Spec.TargetTable", a.ko.Spec.TargetTable, b.ko.Spec.TargetTable)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ViewExpandedText, b.ko.Spec.ViewExpandedText) {
		delta.Add("Spec.ViewExpandedText", a.ko.Spec.ViewExpandedText, b.ko.Spec.ViewExpandedText)
	} else if a.ko.Spec.ViewExpandedText != nil && b.ko.Spec.ViewExpandedText != nil {
		if *a.ko.Spec.ViewExpandedText != *b.ko.Spec.ViewExpandedText {
			delta.Add("Spec.ViewExpandedText", a.ko.Spec.ViewExpandedText, b.ko.Spec.ViewExpandedText)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ViewOriginalText, b.ko.Spec.ViewOriginalText) {
		delta.Add("Spec.ViewOriginalText", a.ko.Spec.ViewOriginalText, b.ko.Spec.ViewOriginalText)
	} else if a.ko.Spec.ViewOriginalText != nil && b.ko.Spec.ViewOriginalText != nil {
		if *a.ko.Spec.ViewOriginalText != *b.ko.Spec.ViewOriginalText {
			delta.Add("Spec.ViewOriginalText", a.ko.Spec.ViewOriginalText, b.ko.Spec.ViewOriginalText)
		}
	}

	return delta
}
