// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package table

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/glue"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/glue-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Table{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetTableOutput
	resp, err = rm.sdkapi.GetTable(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetTable", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "EntityNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	ko := r.ko.DeepCopy()

	if resp.Table.CatalogId != nil {
		ko.Spec.CatalogID = resp.Table.CatalogId
	} else {
		ko.Spec.CatalogID = nil
	}
	if resp.Table.DatabaseName != nil {
		ko.Spec.DatabaseName = resp.Table.DatabaseName
	} else {
		ko.Spec.DatabaseName = nil
	}
	if resp.Table.Description != nil {
		ko.Spec.Description = resp.Table.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.Table.Name != nil {
		ko.Spec.Name = resp.Table.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Table.Owner != nil {
		ko.Spec.Owner = resp.Table.Owner
	} else {
		ko.Spec.Owner = nil
	}
	if resp.Table.Parameters != nil {
		ko.Spec.Parameters = aws.StringMap(resp.Table.Parameters)
	} else {
		ko.Spec.Parameters = nil
	}
	if resp.Table.PartitionKeys != nil {
		cols := []*svcapitypes.Column{}
		for _, col := range resp.Table.PartitionKeys {
			c := &svcapitypes.Column{
				Name:    col.Name,
				Comment: col.Comment,
				Type:    col.Type,
			}
			if col.Parameters != nil {
				c.Parameters = aws.StringMap(col.Parameters)
			}
			cols = append(cols, c)
		}
		ko.Spec.PartitionKeys = cols
	} else {
		ko.Spec.PartitionKeys = nil
	}
	if resp.Table.Retention != 0 {
		ret := int64(resp.Table.Retention)
		ko.Spec.Retention = &ret
	} else {
		ko.Spec.Retention = nil
	}
	if resp.Table.StorageDescriptor != nil {
		ko.Spec.StorageDescriptor = rm.setStorageDescriptor(resp.Table.StorageDescriptor)
	} else {
		ko.Spec.StorageDescriptor = nil
	}
	if resp.Table.TableType != nil {
		ko.Spec.TableType = resp.Table.TableType
	} else {
		ko.Spec.TableType = nil
	}
	if resp.Table.TargetTable != nil {
		ko.Spec.TargetTable = &svcapitypes.TableIdentifier{
			CatalogID:    resp.Table.TargetTable.CatalogId,
			DatabaseName: resp.Table.TargetTable.DatabaseName,
			Name:         resp.Table.TargetTable.Name,
			Region:       resp.Table.TargetTable.Region,
		}
	} else {
		ko.Spec.TargetTable = nil
	}
	if resp.Table.ViewExpandedText != nil {
		ko.Spec.ViewExpandedText = resp.Table.ViewExpandedText
	} else {
		ko.Spec.ViewExpandedText = nil
	}
	if resp.Table.ViewOriginalText != nil {
		ko.Spec.ViewOriginalText = resp.Table.ViewOriginalText
	} else {
		ko.Spec.ViewOriginalText = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	arn := ackv1alpha1.AWSResourceName(tableARN(ko))
	ko.Status.ACKResourceMetadata.ARN = &arn

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil || r.ko.Spec.DatabaseName == nil
}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetTableInput, error) {
	res := &svcsdk.GetTableInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.DatabaseName != nil {
		res.DatabaseName = r.ko.Spec.DatabaseName
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	tableInput, err := rm.buildTableInput(desired)
	if err != nil {
		return nil, err
	}
	input.TableInput = tableInput

	var resp *svcsdk.CreateTableOutput
	_ = resp
	resp, err = rm.sdkapi.CreateTable(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateTable", err)
	if err != nil {
		return nil, err
	}

	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	arn := ackv1alpha1.AWSResourceName(tableARN(ko))
	ko.Status.ACKResourceMetadata.ARN = &arn

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateTableInput, error) {
	res := &svcsdk.CreateTableInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.DatabaseName != nil {
		res.DatabaseName = r.ko.Spec.DatabaseName
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	tableInput, err := rm.buildTableInput(desired)
	if err != nil {
		return nil, err
	}
	input.TableInput = tableInput

	var resp *svcsdk.UpdateTableOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateTable(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateTable", err)
	if err != nil {
		return nil, err
	}

	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateTableInput, error) {
	res := &svcsdk.UpdateTableInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.DatabaseName != nil {
		res.DatabaseName = r.ko.Spec.DatabaseName
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteTableOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteTable(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteTable", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteTableInput, error) {
	res := &svcsdk.DeleteTableInput{}

	if r.ko.Spec.CatalogID != nil {
		res.CatalogId = r.ko.Spec.CatalogID
	}
	if r.ko.Spec.DatabaseName != nil {
		res.DatabaseName = r.ko.Spec.DatabaseName
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Table,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		if err != nil {
			if recoverableCondition == nil {
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true
	}
	return nil, false
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidInputException":
		return true
	default:
		return false
	}
}
