// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package table

import (
	"slices"
	"strings"

	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"

	svcapitypes "github.com/aws-controllers-k8s/glue-controller/apis/v1alpha1"
)

var (
	_ = svcapitypes.Table{}
	_ = acktags.NewTags()
)

// convertToOrderedACKTags converts the tags parameter into 'acktags.Tags' shape.
func convertToOrderedACKTags(tags map[string]*string) (acktags.Tags, []string) {
	result := acktags.NewTags()
	keyOrder := []string{}

	if len(tags) == 0 {
		return result, keyOrder
	}
	for k, v := range tags {
		if v == nil {
			result[k] = ""
		} else {
			result[k] = *v
		}
	}

	return result, keyOrder
}

// fromACKTags converts the tags parameter into map[string]*string shape.
func fromACKTags(tags acktags.Tags, keyOrder []string) map[string]*string {
	result := map[string]*string{}

	_ = keyOrder
	for k, v := range tags {
		result[k] = &v
	}

	return result
}

// ignoreSystemTags ignores tags that have keys that start with "aws:"
// and systemTags defined on startup via the --resource-tags flag.
func ignoreSystemTags(tags acktags.Tags, systemTags []string) {
	for k := range tags {
		if strings.HasPrefix(k, "aws:") ||
			slices.Contains(systemTags, k) {
			delete(tags, k)
		}
	}
}

// syncAWSTags ensures AWS-managed tags from the latest resource state
// are preserved in the desired state.
func syncAWSTags(a acktags.Tags, b acktags.Tags) {
	for k := range b {
		if strings.HasPrefix(k, "aws:") {
			a[k] = b[k]
		}
	}
}
