// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TableSpec defines the desired state of Table.
//
// Represents a collection of related data organized in columns and rows.
type TableSpec struct {

	// The ID of the Data Catalog in which the table resides. If none is provided,
	// the Amazon Web Services account ID is used by default.
	CatalogID *string `json:"catalogID,omitempty"`

	// The name of the catalog database that contains the target table. For Hive
	// compatibility, this name is entirely lowercase.
	//
	// +kubebuilder:validation:Required
	DatabaseName *string `json:"databaseName"`

	// A description of the table.
	Description *string `json:"description,omitempty"`

	// The table name. For Hive compatibility, this is folded to lowercase when it
	// is stored.
	//
	// +kubebuilder:validation:Required
	Name *string `json:"name"`

	// Specifies an open format table (e.g. Apache Iceberg) when creating the table.
	// This field is immutable after creation.
	OpenTableFormatInput *OpenTableFormatInput `json:"openTableFormatInput,omitempty"`

	// The table owner. Included for Apache Hive compatibility. Not used in the
	// normal course of Glue operations.
	Owner *string `json:"owner,omitempty"`

	// These key-value pairs define properties associated with the table.
	Parameters map[string]*string `json:"parameters,omitempty"`

	// A list of partition indexes for the table. The controller reconciles this
	// list by calling CreatePartitionIndex for additions and DeletePartitionIndex
	// for removals. Indexes passed at creation time are created via CreateTableInput.
	PartitionIndexes []*PartitionIndex `json:"partitionIndexes,omitempty"`

	// A list of columns by which the table is partitioned. Only primitive types
	// are supported as partition keys.
	PartitionKeys []*Column `json:"partitionKeys,omitempty"`

	// The retention time for this table.
	Retention *int64 `json:"retention,omitempty"`

	// A storage descriptor containing information about the physical storage of
	// this table.
	StorageDescriptor *StorageDescriptor `json:"storageDescriptor,omitempty"`

	// The type of this table. Glue will create tables with the EXTERNAL_TABLE type.
	// Other services, such as Athena, may create tables with additional table types.
	TableType *string `json:"tableType,omitempty"`

	// A TableIdentifier structure that describes a target table for resource linking.
	TargetTable *TableIdentifier `json:"targetTable,omitempty"`

	// Included for Apache Hive compatibility. Not used in the normal course of
	// Glue operations.
	ViewExpandedText *string `json:"viewExpandedText,omitempty"`

	// Included for Apache Hive compatibility. Not used in the normal course of
	// Glue operations. If the table is a VIRTUAL_VIEW, certain Athena configuration
	// encoded in base64.
	ViewOriginalText *string `json:"viewOriginalText,omitempty"`
}

// TableStatus defines the observed state of Table
type TableStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// Table is the Schema for the Tables API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Table struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TableSpec   `json:"spec,omitempty"`
	Status            TableStatus `json:"status,omitempty"`
}

// TableList contains a list of Table
// +kubebuilder:object:root=true
type TableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Table `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Table{}, &TableList{})
}
